In [1]:
import numpy as np 
import pandas as pd

In [2]:
column_names = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('u.data', sep='\t', names = column_names)

In [3]:
df.head()

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

In [4]:
movie_titles = pd.read_csv('Movie_Id_Titles')
movie_titles.head()

   item_id              title
0        1   Toy Story (1995)
1        2   GoldenEye (1995)
2        3  Four Rooms (1995)
3        4  Get Shorty (1995)
4        5     Copycat (1995)

In [5]:
df = pd.merge(df,movie_titles,on='item_id')
df.head()

   user_id  item_id  rating  timestamp                            title
0        0       50       5  881250949                 Star Wars (1977)
1        0      172       5  881250949  Empire Strikes Back, The (1980)
2        0      133       1  881250949        Gone with the Wind (1939)
3      196      242       3  881250949                     Kolya (1996)
4      186      302       3  891717742         L.A. Confidential (1997)

In [8]:
#Checking the number of users and movies in the dataset
n_users = df.user_id.nunique()
n_items = df.item_id.nunique()

print(f'number of user: {n_users}')
print(f'number of movies: {n_items}')

number of user: 944
number of movies: 1682

In [9]:
#Splitting the data for later evaluation
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df, test_size=0.25)

In [10]:
#Creating a user-item matrix
train_data_matrix = np.zeros((n_users, n_items))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1] = line[3]

test_data_matrix = np.zeros((n_users, n_items))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1] = line[3]

In [11]:
train_data.head() #smjhnay k liy

,user_id,item_id,rating,timestamp,title
28286,348,323,5,886522579,Dante's Peak (1997)
76926,494,358,3,879540901,Spawn (1997)
5703,308,109,3,887738894,Mystery Science Theater 3000: The Movie (1996)
1759,207,192,3,877822350,Raging Bull (1980)
18510,217,1228,2,889070050,Under Siege 2: Dark Territory (1995)

In [14]:
# our user-item matrices, Row: User id, Column: Movie id, Value: the rating user gave
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(944, 1682))

In [13]:
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(944, 1682))

In [17]:
# Cosine similarity(Pairwise function from sklearn), to find the similarity between movies accoring with users. 
# key idea: to find out which movies are similar in user perspective

from sklearn.metrics.pairwise import pairwise_distances
user_similarity =  pairwise_distances(train_data_matrix, metric='cosine')
item_similarity = pairwise_distances(train_data_matrix.T, metric = 'cosine')