In [1]:
import numpy as np 
import pandas as pd

In [14]:
column_names = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('u.data', sep='\t', names = column_names)

In [15]:
df.head()

   user_id  item_id  rating  timestamp
0        0       50       5  881250949
1        0      172       5  881250949
2        0      133       1  881250949
3      196      242       3  881250949
4      186      302       3  891717742

In [16]:
movie_titles = pd.read_csv('Movie_Id_Titles')
movie_titles.head()

   item_id              title
0        1   Toy Story (1995)
1        2   GoldenEye (1995)
2        3  Four Rooms (1995)
3        4  Get Shorty (1995)
4        5     Copycat (1995)

In [17]:
df = pd.merge(df,movie_titles,on='item_id')
df.head()

   user_id  item_id  rating  timestamp                            title
0        0       50       5  881250949                 Star Wars (1977)
1        0      172       5  881250949  Empire Strikes Back, The (1980)
2        0      133       1  881250949        Gone with the Wind (1939)
3      196      242       3  881250949                     Kolya (1996)
4      186      302       3  891717742         L.A. Confidential (1997)

In [18]:
#Checking the number of users and movies in the dataset
n_users = df.user_id.nunique()
n_item = df.item_id.nunique()

print(f'number of user: {n_users}')
print(f'number of movies: {n_item}')

number of user: 944
number of movies: 1682

In [20]:
#Splitting the data for later evaluation
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df, test_size=0.25)